/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-02-03 01:04:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._0202;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.member.MemberVO;
import java.util.List;
import kr.or.ddit.ibatis.config.SqlMapClientFactory;
import com.ibatis.sqlmap.client.SqlMapClientBuilder;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.io.Reader;
import com.ibatis.common.resources.Resources;
import java.nio.charset.Charset;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//1. 외부 라이브러리 추가
	// ojdbc6.jar
	// ibatis-2.3.4.726.jar
	// 2. ibatis 설정파일
	// sqlMapConfig.xml
	// 1. db연결정보
	// 2. alias 설정
	// 3. mapper 등록(sql문)
	// 3. ibatis를 실행하기 위한 객체
	// SqlMapClient 객체를 생성하기 위해서5
	// sqlMapConfig.xml이 필요하다

	// 클라이언트 요청시 전송되는 데이터를 받는다
	// CRUD처리를 한다.
	//- 1. SqlMapClient객체를 얻어오기 - smc = SqlMapClientFactory.getClient();

	//- 2. sql문을 실행 - mapper파일의 namespace.id이름
	//	select -> smc.queryForList(namespace.id이름) 여러줄
	//	select -> smc.quertForObject(namespace.id이름)  한줄

	// 처리 결과로 응답 데이터를 생성한다. - json, text, html, xml

      out.write("\r\n");
      out.write("\r\n");

	//- 1. SqlMapClient객체를 얻어오기 - smc = SqlMapClientFactory.getClient();
	SqlMapClient smc = SqlMapClientFactory.getClient();
	//- 2. sql문을 실행 - mapper파일의 namespace.id이름
	List<MemberVO> list = smc.queryForList("member.selectAll");

      out.write("\r\n");
      out.write("[\r\n");

	//- 3. 실행 결과로 json 데이터 생성
	for (int i = 0; i < list.size(); i++) {
		MemberVO vo = list.get(i);
		if(i>0) out.print(",");

      out.write("\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\"id\" : \"");
      out.print( vo.getMem_id() );
      out.write("\",\r\n");
      out.write("\t\t\"name\" : \"");
      out.print( vo.getMem_name() );
      out.write("\",\r\n");
      out.write("\t\t\"hp\" : \"");
      out.print( vo.getMem_hp() );
      out.write("\",\r\n");
      out.write("\t\t\"mail\" : \"");
      out.print( vo.getMem_mail() );
      out.write("\"\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");

	}

      out.write("\r\n");
      out.write("]\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
